FROM xuxinkun/centos:7
RUN yum update -y && yum install -y tar git curl nano wget dialog net-tools python-distribute python libffi-devel python-pip python-devel gcc openssl-devel libxml-devel libxslt-devel MySQL-python
RUN easy_install -U pip