FROM xuxinkun/centos:centos7
RUN yum update && yum install tar git curl nano wget dialog net-tools python-distribute python libffi-devel python-pip python-devel gcc openssl-devel libxml-devel libxslt-devel
RUN easy_install -U pip