FROM xuxinkun/ubuntu:14.04
RUN apt-get update && apt-get install -y tar git curl nano wget dialog net-tools build-essential libssl-dev libffi-dev python python-dev python-distribute python-pip
RUN easy_install -U pip