FROM index.alauda.cn/xuxinkun/openstack-base-centos
RUN cd / && curl https://raw.githubusercontent.com/openstack/aodh/master/requirements.txt -o requirements.txt
RUN pip install -r /requirements.txt